title: Amagi Media Labs Pvt Ltd
email: supportworkflows@amagi.com
description: >- # this means to ignore newlines until "baseurl:"
  Amagi is a next-generation media technology company that provides cloud broadcast and targeted advertising platforms to TV networks and OTT providers, globally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AmagiCorp
github_username:  amagimedia

# Build settings
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

